### ISSUE TITLE
kBET colors are reversed?

### ISSUE THREAD

**Issue by andrewdchen** [YosefLab/scib-metrics#102]
### Report

Thanks for putting this package together! I have been using it in my own analysis of scRNAseq data. I just noticed that the kBET colors in the plotted table should be reversed? ([Example](https://scib-metrics.readthedocs.io/en/stable/_images/a01bae5e038ea8764ac529f1d66cfe30be9ebcf2bdf65f396917f80a1c6007da.png)) 

High values indicate high average rejection rate of the null hypothesis: batch distribution in a local neighborhood ~ batch distribution in a random neighborhood. So for a batch correction metric, low kbet values should be green instead of purple?

**Comment by adamgayoso** [comment]
In this package, we use the non-rejection rate (colloquially the acceptance rate, though you can only reject the null hypothesis). See here

https://github.com/YosefLab/scib-metrics/blob/5681f7ef6b6d4cfd04fda90d1d33fab1dbe1bb50/src/scib_metrics/_kbet.py#L93

and here

https://github.com/YosefLab/scib-metrics/blob/5681f7ef6b6d4cfd04fda90d1d33fab1dbe1bb50/src/scib_metrics/_kbet.py#L131
