### ISSUE TITLE
Fix random seed in NMI/ARI

### ISSUE THREAD

**Issue by Hrovatin** [YosefLab/scib-metrics#104]
### Description of feature

I think the clustering of NMI/ARI may currently not be fully reproducible due to the lack of setting the random seed.
I think I fixed it with the below:
```
    random.seed(0)
    labels_pred = sm._nmi_ari._compute_clustering_leiden(X, resolution)
```

**Comment by adamgayoso** [comment]
if you seed your script or notebook before running any package code then it should be reproducible. I'm not sure we'd want to change the global seed inside a local function

**Comment by adamgayoso** [comment]
I think something like

```
import random
rng = random.Random(42)
ig.set_random_number_generator(rng)
```

would solve it
