### ISSUE TITLE
JAX one hot error

### ISSUE THREAD

**Issue by robinmittas** [YosefLab/scib-metrics#105]
### Report
Hi,

when running the benchmarker (i.e. `bm.benchmark()`) I recieve a JAX unhashable Type error for the PCR (principal_component_regression). 
PCR is calling the function `utils.one_hot function`, where the line of code `n_classes = n_classes or jnp.max(y) + 1` returns an Array of type jaxlib.xla_extension.ArrayImpl which results in the error as `n_classes` needs to be an int for the `one_hot` transformation and not an array.

My anndata object has a batchkey (covariate) of 2 classes (which is a categorical dtype, I also tried with integer dtypes which resulted in the same error). 
In `utils/_pcr.py` line 44 this code is executed, returning an numpy ndarray with 0s and 1s:
```
if categorical: covariate = np.asarray(pd.Categorical(covariate).codes)
```

Afterwards `one_hot` is executed and `n_classes` doesn't return an `int` resulting in the error message below

I suggest to replace this line by (please refer to the PR https://github.com/YosefLab/scib-metrics/pull/106):
`n_classes = n_classes or int(jnp.max(y) + 1)`

**Detailled Error message:**

File /vol/storage/robin/code/nuc_cyt_reproduce_integration/notebooks/integration_imputation/../../../scib-metrics/src/scib_metrics/benchmark/_core.py:226, in Benchmarker.benchmark(self)
    223 if isinstance(use_metric_or_kwargs, dict):
    224     # Kwargs in this case
    225     metric_fn = partial(metric_fn, **use_metric_or_kwargs)
--> 226 metric_value = getattr(MetricAnnDataAPI, metric_name)(ad, metric_fn)
    227 # nmi/ari metrics return a dict
    228 if isinstance(metric_value, dict):

File /vol/storage/robin/code/nuc_cyt_reproduce_integration/notebooks/integration_imputation/../../../scib-metrics/src/scib_metrics/benchmark/_core.py:91, in MetricAnnDataAPI.<lambda>(ad, fn)
     89 graph_connectivity = lambda ad, fn: fn(ad.obsp["15_distances"], ad.obs[_LABELS])
     90 silhouette_batch = lambda ad, fn: fn(ad.X, ad.obs[_LABELS], ad.obs[_BATCH])
---> 91 pcr_comparison = lambda ad, fn: fn(ad.obsm[_X_PRE], ad.X, ad.obs[_BATCH], categorical=True)
     92 ilisi_knn = lambda ad, fn: fn(ad.obsp["90_distances"], ad.obs[_BATCH])
     93 kbet_per_label = lambda ad, fn: fn(ad.obsp["50_connectivities"], ad.obs[_BATCH], ad.obs[_LABELS])

File /vol/storage/robin/code/nuc_cyt_reproduce_integration/notebooks/integration_imputation/../../../scib-metrics/src/scib_metrics/_pcr_comparison.py:43, in pcr_comparison(X_pre, X_post, covariate, scale, **kwargs)
     40 if covariate.shape[0] != X_pre.shape[0]:
     41     raise ValueError("Dimension mismatch: `X_pre` and `covariate` must have the same number of samples.")
---> 43 pcr_pre = principal_component_regression(X_pre, covariate, **kwargs)
     44 pcr_post = principal_component_regression(X_post, covariate, **kwargs)
     46 if scale:

File /vol/storage/robin/code/nuc_cyt_reproduce_integration/notebooks/integration_imputation/../../../scib-metrics/src/scib_metrics/utils/_pcr.py:49, in principal_component_regression(X, covariate, categorical, n_components)
     46 else:
     47     covariate = np.asarray(covariate)
---> 49 covariate = one_hot(covariate) if categorical else covariate.reshape((covariate.shape[0], 1))
     51 pca_results = pca(X, n_components=n_components)
     53 # Center inputs for no intercept

File /vol/storage/robin/code/nuc_cyt_reproduce_integration/notebooks/integration_imputation/../../../scib-metrics/src/scib_metrics/utils/_utils.py:39, in one_hot(y, n_classes)
     36 # n_classes = n_classes or int(jnp.max(y) + 1)
     37 n_classes = n_classes or jnp.max(y) + 1
---> 39 return nn.one_hot(jnp.ravel(y), n_classes)

File /vol/storage/miniconda3/envs/conda_env_robin/lib/python3.9/site-packages/jax/_src/nn/functions.py:464, in one_hot(x, num_classes, dtype, axis)
    438 """One-hot encodes the given indices.
    439 
    440 Each index in the input ``x`` is encoded as a vector of zeros of length
   (...)
    459     computed.
    460 """
    461 num_classes = core.concrete_dim_or_error(
    462     num_classes,
    463     "The error arose in jax.nn.one_hot argument `num_classes`.")
--> 464 return _one_hot(x, num_classes, dtype=dtype, axis=axis)

ValueError: Non-hashable static arguments are not supported. An error occurred during a call to '_one_hot' while trying to hash an object of type <class 'jaxlib.xla_extension.ArrayImpl'>, 2. The error was:
TypeError: unhashable type: 'ArrayImpl'

### Version information

-----
anndata             0.9.2
jax                 0.4.14
jaxlib              0.4.14
numpy               1.24.4
pandas              2.1.0
plottable           0.1.5
scanpy              1.9.3
scib_metrics        1
scvelo              0.2.6.dev38+g4c7fbd7.d20230914
session_info        1.0.0
-----

**Comment by jesswhitts** [comment]
Same error here!

**Comment by robinmittas** [comment]
Hi @jesswhitts, I resolved it by uninstalling the package via pip, then cloning the repo into my working directory, adjusting the line of code as in this PR https://github.com/YosefLab/scib-metrics/pull/106. And then via 
``` 
sys.path.append("../../../scib-metrics/src/")
from scib_metrics.benchmark import Benchmarker, BioConservation
```
you can import the package. It might be that in `/src/scib_metrics/__init__.py` you further need to replace this line of code ```__version__ = version("scib-metrics")``` by for example ```__version__ = 1```
