### ISSUE TITLE
Incorrect return type in the documentation for ilisi/clisi

### ISSUE THREAD

**Issue by timtreis** [YosefLab/scib-metrics#113]
### Report

Extremely minor but I'm currently extracting a few bits from "under the hood". Noticed that the return type of the `ilisi_knn` and `clisi_knn` calculations are incorrect. According to https://scib-metrics.readthedocs.io/en/stable/generated/scib_metrics.ilisi_knn.html it's `ilisi Array of shape (n_cells,) with the iLISI score for each cell.` but due to https://github.com/YosefLab/scib-metrics/blob/9d109007d8b78ad2678342db6630cc355cfd1d0b/src/scib_metrics/_lisi.py#L66 it's a single float. Analog for clisi

**Comment by adamgayoso** [comment]
Thanks! Happy to accept a PR with the change
