### ISSUE TITLE
progress bar not moving 

### ISSUE THREAD

**Issue by Flu09** [YosefLab/scib-metrics#175]
### Report

>>> bm = Benchmarker(
...     obj,
...     batch_key="dataset",
...     label_key="celltypes,
...     embedding_obsm_keys=["unintegrated", "cca", "rpca", "harmony", "scvi"],
...     n_jobs=29,
... )
>>> bm.benchmark()
Computing neighbors: 100%|██████████| 5/5 [41:56<00:00, 503.33s/it]
Embeddings:   0%|          | 0/5 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]

It has been like that for 12 hours now. I am not sure how long it is supposed to take. The cells are 1.3 million.  I will appreciate it if you can help. Also how to import seurat v5 cca embedding into the adata object please ? 

### Version information

scib-metrics: 0.5.1
anndata: 0.10.8
chex: 0.1.85
igraph: 0.10.8
jax: 0.4.25
jaxlib: 0.4.25
matplotlib: 3.8.3
numpy: 1.26.4
pandas: 2.2.1
plottable: 0.1.5
pynndescent: 0.5.11
rich: 13.7.1
scanpy: 1.9.8
scikit-learn: 1.4.1.post1
scipy: 1.11.4
tqdm: 4.66.2
umap-learn: 0.5.5
texttable: 1.7.0
get-annotations: 0.1.2
h5py: 3.10.0
joblib: 1.3.2
natsort: 8.4.0
networkx: 3.2.1
numba: 0.59.0
packaging: 23.2
patsy: 0.5.6
seaborn: 0.13.2
session-info: 1.0.0
statsmodels: 0.14.1
array-api-compat: 1.4.1
exceptiongroup: 1.2.0
contourpy: 1.2.0
cycler: 0.12.1
fonttools: 4.49.0
kiwisolver: 1.4.5
pillow: 10.2.0
pyparsing: 3.1.2
python-dateutil: 2.9.0.post0
importlib-resources: 6.1.2
pytz: 2024.1
tzdata: 2024.1
threadpoolctl: 3.3.0
llvmlite: 0.42.0
absl-py: 2.1.0
typing-extensions: 4.10.0
toolz: 0.12.1
ml-dtypes: 0.3.2
opt-einsum: 3.3.0
importlib-metadata: 6.11.0
markdown-it-py: 3.0.0
pygments: 2.17.2
zipp: 3.17.0
mdurl: 0.1.2
six: 1.16.0
stdlib-list: 0.10.0

**Comment by canergen** [comment]
Hi, see my response on discourse.
