### ISSUE TITLE
Memory issue for ASW scores

### ISSUE THREAD

**Issue by mumichae** [YosefLab/scib-metrics#36]
Hi,

thanks for the cool reimplementation if the scib metrics!
I've tried out the ASW metrics (label and batch) on a 700MB anndata object but get out-of-memory errors even at 10GB. Is there potentially a memory leak?

Best,
Michaela

**Comment by adamgayoso** [comment]
Thanks for testing, how did you install the package?

**Comment by adamgayoso** [comment]
Also what input are you running on? I.e., what is the dimension of the input.

**Comment by adamgayoso** [comment]
In the latest release (0.0.5) just made now we have an updated ASW calculation. Please let me know if it works for you! We designed it to work well on embedding inputs that are not super high dimensional!

**Comment by adamgayoso** [comment]
this is definitely fixed in version 0.0.6 `pip install scib-metrics==0.0.6`
