### ISSUE TITLE
Large memory issue for ARI/NMI with kmeans

### ISSUE THREAD

**Issue by mumichae** [YosefLab/scib-metrics#50]
Similar to #36 :
Working with version 0.0.6 on the same dataset as in #36, I am still getting huge memory consumption (exceeding 90GB).
The dataset isn't particularly huge (2.8GB dense, ~500MB sparse).

**Comment by adamgayoso** [comment]
This is fixed on the main branch!

**Comment by adamgayoso** [comment]
See #49

**Comment by mumichae** [comment]
Thanks, I'm not getting any memory errors anymore. However, the k-means metrics seem to take considerably longer, even on GPU
![image](https://user-images.githubusercontent.com/51025211/201519990-d6e3481c-e0b7-4b80-8ed3-62b8e3bb3ecb.png)

metrics with `_y` are from `scib_metrics`, the rest from `scib`

**Comment by adamgayoso** [comment]
Thanks we will have a look (cc @martinkim0). Note that also the first time each method runs it needs to compile (and recompiles for each new embedding shape). So for example if you have two methods giving (n_cells, 50), running the metrics on the second method's output will be considerably faster.

**Comment by adamgayoso** [comment]
We figured out the issue with kmeans (#55). For now we are switching to a faster initialization
