### ISSUE TITLE
How to compute all features' metrics 

### ISSUE THREAD

**Issue by GlancerZ** [YosefLab/scib-metrics#91]
There is an example that how to use this function to compute integration results on embedding space, shall we use this to compute metrics on full data (feature space)?

**Comment by adamgayoso** [comment]
This package is optimized around embeddings. Many metrics are distance based. Therefore, you can always run PCA and keep 100s of PCs, which should explain most of the variation in your data.

**Comment by adamgayoso** [comment]
thanks, I don't anticipate this coming soon but it's a distinctly real possibility :)
